global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
    
  - job_name: 'otel-collector'
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['otel-collector:9464']
  
  - job_name: jaeger
    static_configs:
      - targets: ['jaeger:14269']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']