FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app


COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN  go build -o app ./cmd/main.go

FROM alpine:3.18

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/app .

EXPOSE 8081
ENTRYPOINT ["./app"]
