services:
  ticket-service:
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/ticket_db?sslmode=disable
    networks:
      - ticket-network

  postgres:
    image: postgres:latest
    container_name: postgres_ticket_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticket_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticket_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ticket-network
    restart: unless-stopped
  
  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "16686:16686"  # UI
      - "4318:4318"    # OTLP HTTP

volumes:
  pgdata:
    driver: local

networks:
  ticket-network:
    driver: bridge