services:
  booking-service:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5430
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: booking_db
    networks:
      - ticket-network
    

  postgres:
    image: postgres:latest
    container_name: postgres_booking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking_db
    ports:
      - "5430:5430"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ticket-network
    restart: unless-stopped

volumes:
  pgdata:
    driver: local

networks:
  ticket-network:
    driver: bridge