FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./
RUN go build -o app ./main.go

FROM gcr.io/distroless/base-debian11
WORKDIR /app
COPY --from=builder /app/app .

ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["/app/app"]
