
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /booking-service ./cmd/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /booking-service .

RUN apk --no-cache add ca-certificates

CMD ["./booking-service"]