
services:
  saga-service:
    build: ./
    ports:
      - "8085:8085"
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    restart: unless-stopped
    networks:
    - monitoring
  
  temporal:
    image: temporalio/auto-setup:1.22
    ports:
      - "7233:7233" # Порт Temporal Frontend
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-db
    depends_on:
      - temporal-db
    networks:
    - monitoring
      

  temporal-db:
    image: postgres:13
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    volumes:
      - temporal_pgdata:/var/lib/postgresql/data
    networks:
    - monitoring

  temporal-web:
    image: temporalio/web:latest
    ports:
      - "8088:8088"
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
    depends_on:
      - temporal

networks:
  monitoring:
    driver: bridge

volumes:
  temporal_pgdata:
